import "react-native-url-polyfill/auto";
import React, { useCallback, useEffect, useMemo, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { ActivityIndicator, Alert, Image, KeyboardAvoidingView, Platform, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaProvider, SafeAreaView } from "react-native-safe-area-context";
import * as DocumentPicker from "expo-document-picker";
import { api, apiBaseUrl } from "./src/api";
import { hasSupabaseConfig, supabase } from "./src/supabase";
import { nextVisitCheckpoint, partitionNurseJobs } from "./src/workspace";

const brand = require("./assets/brand/nursebridges-care-mark.png");
type Tab = "home" | "opportunities" | "schedule" | "messages" | "account";
type Job = { id: string; title: string; description: string | null; status: string; start_time: string | null; service_city?: string | null; service_state?: string | null; assigned_nurse_user_id?: string | null; logistics?: Record<string, unknown> | null };
type Application = { id: string; job_id: string; status: string };
type Workspace = { profile: null | { verification_status: string; onboarding_step: string; professional_summary: string | null; years_experience: number | null; service_radius_miles: number | null; availability_status: string }; availability: Array<{ id: string; starts_at: string; ends_at: string }>; earnings: unknown[]; payments_enabled: false; payments_message: string };
type Visit = { events: Array<{ id: string; event_type: string; occurred_at: string }>; report: null | { status: string; visit_summary: string | null; provider_instructions: string | null; follow_up_tasks: string | null; transportation_outcome: string | null } };
type Notification = { id: string; title: string; body: string | null; created_at: string; read_at: string | null };
type SupportCase = { id: string; title: string; case_type: string; status: string; priority: string; created_at: string };

const tabs: Array<{ key: Tab; label: string }> = [{ key: "home", label: "Home" }, { key: "opportunities", label: "Opportunities" }, { key: "schedule", label: "Schedule" }, { key: "messages", label: "Messages" }, { key: "account", label: "Account" }];
const titleCase = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

function Button({ label, onPress, secondary, disabled }: { label: string; onPress: () => void; secondary?: boolean; disabled?: boolean }) {
  return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[styles.button, secondary && styles.buttonSecondary, disabled && styles.disabled]}><Text style={[styles.buttonText, secondary && styles.buttonTextSecondary]}>{label}</Text></Pressable>;
}

function Field({ label, value, onChangeText, multiline, keyboardType }: { label: string; value: string; onChangeText: (value: string) => void; multiline?: boolean; keyboardType?: "default" | "number-pad" | "email-address" }) {
  return <View style={styles.field}><Text style={styles.fieldLabel}>{label}</Text><TextInput style={[styles.input, multiline && styles.multiline]} value={value} onChangeText={onChangeText} multiline={multiline} keyboardType={keyboardType} placeholderTextColor="#78909a" /></View>;
}

function Card({ children }: { children: React.ReactNode }) { return <View style={styles.card}>{children}</View>; }

export default function App() {
  const [session, setSession] = useState<Session | null>(null);
  const [role, setRole] = useState<string | null>(null);
  const [tab, setTab] = useState<Tab>("home");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [workspace, setWorkspace] = useState<Workspace | null>(null);
  const [jobs, setJobs] = useState<Job[]>([]);
  const [applications, setApplications] = useState<Application[]>([]);
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [supportCases, setSupportCases] = useState<SupportCase[]>([]);
  const [selectedJob, setSelectedJob] = useState<Job | null>(null);
  const [visit, setVisit] = useState<Visit>({ events: [], report: null });
  const [summary, setSummary] = useState("");
  const [instructions, setInstructions] = useState("");
  const [followUp, setFollowUp] = useState("");
  const [transportOutcome, setTransportOutcome] = useState("");
  const [arrivalPin, setArrivalPin] = useState("");
  const [professionalSummary, setProfessionalSummary] = useState("");
  const [years, setYears] = useState("");
  const [radius, setRadius] = useState("");
  const [supportTitle, setSupportTitle] = useState("");
  const [supportDescription, setSupportDescription] = useState("");

  const load = useCallback(async (activeSession: Session) => {
    const me = await api<{ role: string }>(activeSession, "/me");
    setRole(me.role);
    if (me.role !== "nurse") return;
    const [workspaceData, jobsData, applicationsData, notificationsData, casesData] = await Promise.all([
      api<Workspace>(activeSession, "/nurse/workspace"),
      api<{ jobs: Job[] }>(activeSession, "/jobs").catch(() => ({ jobs: [] })),
      api<{ applications: Application[] }>(activeSession, "/v1/applications"),
      api<{ notifications: Notification[] }>(activeSession, "/notifications"),
      api<{ cases: SupportCase[] }>(activeSession, "/support-cases")
    ]);
    setWorkspace(workspaceData); setJobs(jobsData.jobs); setApplications(applicationsData.applications); setNotifications(notificationsData.notifications); setSupportCases(casesData.cases);
    setProfessionalSummary(workspaceData.profile?.professional_summary ?? "");
    setYears(workspaceData.profile?.years_experience?.toString() ?? "");
    setRadius(workspaceData.profile?.service_radius_miles?.toString() ?? "");
  }, []);

  useEffect(() => {
    if (!supabase) { setLoading(false); return; }
    void supabase.auth.getSession().then(({ data }) => { setSession(data.session); if (data.session) return load(data.session); }).catch(() => setError("Unable to restore your secure session.")).finally(() => setLoading(false));
    const { data } = supabase.auth.onAuthStateChange((_event, nextSession) => { setSession(nextSession); if (nextSession) void load(nextSession); else setRole(null); });
    return () => data.subscription.unsubscribe();
  }, [load]);

  const jobPartitions = useMemo(() => partitionNurseJobs(jobs, session?.user.id ?? ""), [jobs, session]);
  const assignedJobs = jobPartitions.assigned;
  const openJobs = jobPartitions.opportunities;
  const applicationByJob = useMemo(() => new Map(applications.map((item) => [item.job_id, item])), [applications]);
  const approved = workspace?.profile?.verification_status === "approved";

  const refresh = async () => { if (!session) return; setRefreshing(true); setError(null); try { await load(session); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to refresh."); } finally { setRefreshing(false); } };
  const signIn = async () => { if (!supabase) return; setBusy(true); setError(null); const { error: signInError } = await supabase.auth.signInWithPassword({ email: email.trim(), password }); if (signInError) setError(signInError.message); setBusy(false); };

  const loadVisit = async (job: Job) => { if (!session) return; setSelectedJob(job); const data = await api<Visit>(session, `/jobs/${job.id}/visit`); setVisit(data); setSummary(data.report?.visit_summary ?? ""); setInstructions(data.report?.provider_instructions ?? ""); setFollowUp(data.report?.follow_up_tasks ?? ""); setTransportOutcome(data.report?.transportation_outcome ?? ""); };
  const apply = async (job: Job) => { if (!session) return; setBusy(true); try { await api(session, `/jobs/${job.id}/apply`, { method: "POST", body: JSON.stringify({ note: "Available and interested through NurseBridges Care." }) }); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to apply."); } finally { setBusy(false); } };
  const recordCheckpoint = async (eventType: string) => { if (!session || !selectedJob) return; setBusy(true); try { await api(session, `/jobs/${selectedJob.id}/visit/events`, { method: "POST", body: JSON.stringify({ event_type: eventType }) }); await loadVisit(selectedJob); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to record checkpoint."); } finally { setBusy(false); } };
  const verifyPin = async () => { if (!session || !selectedJob) return; setBusy(true); try { await api(session, `/jobs/${selectedJob.id}/arrival-pin/verify`, { method: "POST", body: JSON.stringify({ pin: arrivalPin }) }); setArrivalPin(""); Alert.alert("Arrival confirmed", "The patient-provided PIN was verified."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to verify arrival."); } finally { setBusy(false); } };
  const saveReport = async (status: "draft" | "submitted") => { if (!session || !selectedJob) return; setBusy(true); try { await api(session, `/jobs/${selectedJob.id}/visit/report`, { method: "PUT", body: JSON.stringify({ status, visit_summary: summary, provider_instructions: instructions, follow_up_tasks: followUp, transportation_outcome: transportOutcome }) }); await loadVisit(selectedJob); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to save report."); } finally { setBusy(false); } };
  const completeVisit = async () => { if (!session || !selectedJob) return; setBusy(true); try { await api(session, `/jobs/${selectedJob.id}/complete`, { method: "PATCH" }); setSelectedJob(null); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to complete care."); } finally { setBusy(false); } };
  const saveProfile = async () => { if (!session) return; setBusy(true); try { await api(session, "/nurse/workspace/profile", { method: "PUT", body: JSON.stringify({ professional_summary: professionalSummary, years_experience: years ? Number(years) : undefined, service_radius_miles: radius ? Number(radius) : undefined, availability_status: workspace?.profile?.availability_status ?? "unavailable", onboarding_step: "availability" }) }); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to save profile."); } finally { setBusy(false); } };
  const addAvailability = async () => { if (!session) return; const starts = new Date(); const ends = new Date(starts.getTime() + 8 * 60 * 60 * 1000); setBusy(true); try { await api(session, "/nurse/workspace/availability", { method: "PUT", body: JSON.stringify({ windows: [{ starts_at: starts.toISOString(), ends_at: ends.toISOString(), timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, recurrence: "none" }] }) }); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to update availability."); } finally { setBusy(false); } };
  const uploadCredential = async () => { if (!session || !supabase) return; const result = await DocumentPicker.getDocumentAsync({ copyToCacheDirectory: true, type: ["application/pdf", "image/*"] }); if (result.canceled) return; const asset = result.assets[0]; const path = `${session.user.id}/${Date.now()}-${asset.name.replace(/[^a-zA-Z0-9._-]/g, "-")}`; setBusy(true); try { const signed = await api<{ bucket: string; path: string; token: string }>(session, "/nurse/verification-documents/upload-url", { method: "POST", body: JSON.stringify({ storage_path: path }) }); const blob = await (await fetch(asset.uri)).blob(); const { error: uploadError } = await supabase.storage.from(signed.bucket).uploadToSignedUrl(signed.path, signed.token, blob, { contentType: asset.mimeType ?? "application/octet-stream" }); if (uploadError) throw uploadError; await api(session, "/nurse/verification-documents", { method: "POST", body: JSON.stringify({ storage_path: path, document_type: "rn_license" }) }); Alert.alert("Submitted", "Your credential was uploaded for private review."); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to upload credential."); } finally { setBusy(false); } };
  const createSupportCase = async (caseType: "support" | "incident") => { if (!session || !supportTitle.trim()) return; setBusy(true); try { await api(session, "/support-cases", { method: "POST", body: JSON.stringify({ case_type: caseType, subject_type: selectedJob ? "job" : "account", subject_id: selectedJob?.id, title: supportTitle, description: supportDescription, priority: caseType === "incident" ? "urgent" : "normal" }) }); setSupportTitle(""); setSupportDescription(""); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to contact support."); } finally { setBusy(false); } };

  if (loading) return <SafeAreaProvider><SafeAreaView style={styles.center}><ActivityIndicator color="#20b7aa" /><Text>Preparing NurseBridges Care…</Text></SafeAreaView></SafeAreaProvider>;
  if (!hasSupabaseConfig) return <SafeAreaProvider><SafeAreaView style={styles.center}><Text style={styles.title}>Configuration required</Text><Text style={styles.body}>Secure authentication is not configured for this build.</Text></SafeAreaView></SafeAreaProvider>;
  if (!session) return <SafeAreaProvider><SafeAreaView style={styles.page}><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.login}><Image source={brand} style={styles.logo} /><Text style={styles.eyebrow}>NURSEBRIDGES CARE</Text><Text style={styles.hero}>Professional care workspace</Text><Text style={styles.body}>Sign in with your approved nurse account. Patient accounts cannot enter this application.</Text><Field label="Email" value={email} onChangeText={setEmail} keyboardType="email-address" /><Field label="Password" value={password} onChangeText={setPassword} />{error ? <Text style={styles.error}>{error}</Text> : null}<Button label={busy ? "Signing in…" : "Sign in"} onPress={() => void signIn()} disabled={busy} /></KeyboardAvoidingView></SafeAreaView></SafeAreaProvider>;
  if (role && role !== "nurse") return <SafeAreaProvider><SafeAreaView style={styles.center}><Image source={brand} style={styles.logoSmall} /><Text style={styles.title}>Nurse account required</Text><Text style={styles.body}>This application is exclusively for approved NurseBridges care professionals.</Text><Button label="Sign out" onPress={() => void supabase?.auth.signOut()} /></SafeAreaView></SafeAreaProvider>;

  const nextCheckpoint = nextVisitCheckpoint(visit.events);
  return <SafeAreaProvider><SafeAreaView style={styles.page}><View style={styles.header}><View style={styles.brandRow}><Image source={brand} style={styles.logoSmall} /><View><Text style={styles.brandName}>NurseBridges Care</Text><Text style={styles.brandMeta}>{approved ? "Approved professional" : `Review: ${workspace?.profile?.verification_status ?? "pending"}`}</Text></View></View><Text style={styles.apiLabel}>{apiBaseUrl.replace("https://", "")}</Text></View>{error ? <Pressable onPress={() => setError(null)} style={styles.errorBanner}><Text style={styles.error}>{error}</Text></Pressable> : null}<ScrollView style={styles.scroll} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void refresh()} />}>
    {tab === "home" ? <><Text style={styles.eyebrow}>TODAY</Text><Text style={styles.hero}>{assignedJobs.length ? "Your next visit is ready." : approved ? "You’re ready for care opportunities." : "Complete your professional readiness."}</Text><Card><Text style={styles.cardLabel}>READINESS</Text><Text style={styles.cardTitle}>{workspace?.profile?.verification_status ? titleCase(workspace.profile.verification_status) : "Profile required"}</Text><Text style={styles.body}>{approved ? `${workspace?.availability.length ?? 0} upcoming availability window(s).` : "Submit credentials and availability for operator review."}</Text><Button label={approved ? "Review opportunities" : "Continue onboarding"} onPress={() => setTab(approved ? "opportunities" : "account")} /></Card>{assignedJobs.map((job) => <Card key={job.id}><Text style={styles.cardLabel}>ASSIGNED VISIT</Text><Text style={styles.cardTitle}>{job.title}</Text><Text style={styles.body}>{job.start_time ? new Date(job.start_time).toLocaleString() : "Schedule being confirmed"}</Text><Button label="Open active visit" onPress={() => { setTab("schedule"); void loadVisit(job); }} /></Card>)}</> : null}
    {tab === "opportunities" ? <><Text style={styles.eyebrow}>QUALIFIED OPPORTUNITIES</Text><Text style={styles.title}>Available care</Text>{!approved ? <Card><Text style={styles.cardTitle}>Approval required</Text><Text style={styles.body}>Opportunities remain private until credential review is complete.</Text></Card> : openJobs.map((job) => <Card key={job.id}><Text style={styles.cardTitle}>{job.title}</Text><Text style={styles.body}>{[job.service_city, job.service_state].filter(Boolean).join(", ") || "Service area shared after review"}</Text><Text style={styles.body}>{job.start_time ? new Date(job.start_time).toLocaleString() : "Time to be confirmed"}</Text><Button label={applicationByJob.has(job.id) ? titleCase(applicationByJob.get(job.id)!.status) : "Apply"} onPress={() => void apply(job)} disabled={busy || applicationByJob.has(job.id)} /></Card>)}</> : null}
    {tab === "schedule" ? <><Text style={styles.eyebrow}>SCHEDULE & ACTIVE CARE</Text><Text style={styles.title}>Assigned visits</Text>{assignedJobs.map((job) => <Card key={job.id}><Text style={styles.cardTitle}>{job.title}</Text><Button label="Open visit workspace" onPress={() => void loadVisit(job)} /></Card>)}{selectedJob ? <Card><Text style={styles.cardLabel}>ACTIVE VISIT</Text><Text style={styles.cardTitle}>{selectedJob.title}</Text>{selectedJob.logistics ? <Text style={styles.body}>Private arrival and transportation details are available for this assigned visit.</Text> : null}<Field label="Patient arrival PIN" value={arrivalPin} onChangeText={setArrivalPin} keyboardType="number-pad" /><Button label="Verify arrival PIN" onPress={() => void verifyPin()} disabled={busy || arrivalPin.length !== 6} />{nextCheckpoint ? <Button label={`Record: ${titleCase(nextCheckpoint)}`} onPress={() => void recordCheckpoint(nextCheckpoint)} disabled={busy} secondary /> : <Text style={styles.success}>All visit checkpoints recorded.</Text>}<Text style={styles.sectionTitle}>Visit report</Text><Field label="Visit summary" value={summary} onChangeText={setSummary} multiline /><Field label="Source-attributed provider instructions" value={instructions} onChangeText={setInstructions} multiline /><Field label="Follow-up tasks" value={followUp} onChangeText={setFollowUp} multiline /><Field label="Transportation and handoff outcome" value={transportOutcome} onChangeText={setTransportOutcome} multiline /><Button label="Save draft" onPress={() => void saveReport("draft")} secondary disabled={busy} /><Button label="Submit report" onPress={() => void saveReport("submitted")} disabled={busy || !summary.trim()} /><Button label="Complete care" onPress={() => void completeVisit()} disabled={busy || nextCheckpoint !== undefined || visit.report?.status !== "submitted"} /></Card> : null}</> : null}
    {tab === "messages" ? <><Text style={styles.eyebrow}>COMMUNICATION & SAFETY</Text><Text style={styles.title}>Updates and support</Text>{notifications.map((item) => <Card key={item.id}><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.body}>{item.body ?? ""}</Text><Text style={styles.meta}>{new Date(item.created_at).toLocaleString()}</Text></Card>)}<Card><Text style={styles.cardTitle}>Contact operations</Text><Field label="What do you need?" value={supportTitle} onChangeText={setSupportTitle} /><Field label="Practical details" value={supportDescription} onChangeText={setSupportDescription} multiline /><Button label="Request support" onPress={() => void createSupportCase("support")} disabled={busy || !supportTitle.trim()} /><Button label="Report urgent incident" onPress={() => void createSupportCase("incident")} disabled={busy || !supportTitle.trim()} secondary /></Card>{supportCases.map((item) => <Card key={item.id}><Text style={styles.cardLabel}>{titleCase(item.case_type)} · {titleCase(item.priority)}</Text><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.body}>{titleCase(item.status)}</Text></Card>)}</> : null}
    {tab === "account" ? <><Text style={styles.eyebrow}>PROFESSIONAL PROFILE</Text><Text style={styles.title}>Readiness and availability</Text><Card><Field label="Professional summary" value={professionalSummary} onChangeText={setProfessionalSummary} multiline /><Field label="Years of RN experience" value={years} onChangeText={setYears} keyboardType="number-pad" /><Field label="Service radius (miles)" value={radius} onChangeText={setRadius} keyboardType="number-pad" /><Button label="Save profile" onPress={() => void saveProfile()} disabled={busy} /><Button label="Upload RN credential" onPress={() => void uploadCredential()} secondary disabled={busy} /><Button label="Available for the next 8 hours" onPress={() => void addAvailability()} secondary disabled={busy} /></Card><Card><Text style={styles.cardLabel}>EARNINGS</Text><Text style={styles.cardTitle}>Payouts not yet enabled</Text><Text style={styles.body}>{workspace?.payments_message ?? "Commercial records remain disabled pending approval."}</Text></Card><Button label="Sign out" onPress={() => void supabase?.auth.signOut()} secondary /></> : null}
  </ScrollView><View style={styles.tabBar}>{tabs.map((item) => <Pressable key={item.key} onPress={() => setTab(item.key)} style={styles.tab}><Text style={[styles.tabText, tab === item.key && styles.tabTextActive]}>{item.label}</Text></Pressable>)}</View>{busy ? <View style={styles.busy}><ActivityIndicator color="#fff" /></View> : null}</SafeAreaView></SafeAreaProvider>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: "#f3f7f5" }, center: { flex: 1, justifyContent: "center", alignItems: "center", padding: 28, gap: 16, backgroundColor: "#f3f7f5" }, login: { flex: 1, justifyContent: "center", padding: 28, gap: 14 }, logo: { width: 96, height: 96, alignSelf: "center", marginBottom: 8 }, logoSmall: { width: 48, height: 48 }, header: { backgroundColor: "#071f27", paddingHorizontal: 20, paddingVertical: 14, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, brandRow: { flexDirection: "row", alignItems: "center", gap: 12 }, brandName: { color: "#fff", fontWeight: "800", fontSize: 18 }, brandMeta: { color: "#9ec1c5", fontSize: 12 }, apiLabel: { color: "#6d9398", fontSize: 9 }, scroll: { flex: 1 }, content: { padding: 20, paddingBottom: 120, gap: 14 }, eyebrow: { color: "#0b8f83", fontWeight: "800", letterSpacing: 1.2, fontSize: 12 }, hero: { color: "#071f27", fontWeight: "900", fontSize: 32, lineHeight: 38 }, title: { color: "#071f27", fontWeight: "900", fontSize: 26 }, sectionTitle: { color: "#071f27", fontWeight: "800", fontSize: 19, marginTop: 12 }, body: { color: "#4e6669", fontSize: 15, lineHeight: 22 }, meta: { color: "#78909a", fontSize: 12 }, card: { backgroundColor: "#fff", borderRadius: 22, padding: 18, gap: 12, borderWidth: 1, borderColor: "#d8e4e1" }, cardLabel: { color: "#0b8f83", fontWeight: "800", fontSize: 11, letterSpacing: 1 }, cardTitle: { color: "#071f27", fontWeight: "800", fontSize: 20 }, field: { gap: 7 }, fieldLabel: { color: "#18363b", fontWeight: "700", fontSize: 14 }, input: { backgroundColor: "#edf3f1", borderWidth: 1, borderColor: "#d2dfdc", borderRadius: 14, paddingHorizontal: 14, paddingVertical: 13, color: "#071f27", fontSize: 16 }, multiline: { minHeight: 96, textAlignVertical: "top" }, button: { backgroundColor: "#0b8f83", borderRadius: 14, paddingVertical: 14, paddingHorizontal: 18, alignItems: "center" }, buttonSecondary: { backgroundColor: "#e2f2ef", borderWidth: 1, borderColor: "#87c7bf" }, buttonText: { color: "#fff", fontWeight: "800", fontSize: 15 }, buttonTextSecondary: { color: "#076a63" }, disabled: { opacity: 0.45 }, errorBanner: { backgroundColor: "#ffe7e4", padding: 12 }, error: { color: "#a92d24", fontWeight: "700" }, success: { color: "#08775f", fontWeight: "800" }, tabBar: { flexDirection: "row", backgroundColor: "#fff", borderTopWidth: 1, borderTopColor: "#d8e4e1", paddingVertical: 12, paddingHorizontal: 6 }, tab: { flex: 1, alignItems: "center", paddingVertical: 8 }, tabText: { color: "#718588", fontSize: 11, fontWeight: "700" }, tabTextActive: { color: "#0b8f83" }, busy: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(7,31,39,.25)", alignItems: "center", justifyContent: "center" } });
